### PR TITLE
platform/mikro-e: add support for custom D0 pin interrupts

### PR DESCRIPTION
**Pull request by mtusnio**

### CODE REVIEW

**Comment by nikhil-zinjurde-imgtec** [comment]
Re-write the commit message "platform/mikro-e: add support for custom D0 pin interrupts". Also could you explain the use of this change in a comment?

**Comment by mtusnio** [comment]
Will change the commit.

It's mainly to avoid having to change Contiki files to add interrupts - at the moment all interrupts are implemented using hardcoded defines and such, in the end I'd prefer to change all of them to function pointers to let the users override them in code, rather than having to modify base files. With this code you can have your own interrupt simply by calling the INTERRUPT config macros, and then setting the pointer.

**Comment by nikhil-zinjurde-imgtec** [comment]
test with jenkins - dev

**Comment by nikhil-zinjurde-imgtec** [comment]
Verified

**Pull request merged**
