### PR TITLE
core/dev/leds: Added explicit defines for LD1/LD2

### PR DESCRIPTION
**Pull request by mtusnio**

### CODE REVIEW

**Comment by nikhil-zinjurde-imgtec** [comment]
test with jenkins

**Comment by pratik-prajapati-imgtec** [comment]
Approved

**Comment by manohar-narkhede-imgtec** [comment]
Why the change is required in common Contiki source code? The LEDs are already mapped as LED1 and LED2 in https://github.com/Creatordev/contiki/blob/3.0-mikro-e/platform/mikro-e/contiki-conf.h according to Clicker.

**Comment by mtusnio** [comment]
You're right! I completely missed that, some of the examples (project 1's LED app specifically) still map LED_GREEN/LED_RED to that instead of the project confs, hence the confusion.

**Pull request closed without merging**
