### PR TITLE
platform/mikro-e: add support for Pickle defines

### PR DESCRIPTION
**Pull request by mtusnio**

### CODE REVIEW

**Review by nikhil-zinjurde-imgtec — CHANGES_REQUESTED** [review]
Please update https://github.com/CreatorDev/contiki/blob/3.0-mikro-e/platform/mikro-e/Readme.md to include the use of Pickle defines

**Comment by mtusnio** [comment]
Updated

**Comment by nikhil-zinjurde-imgtec** [comment]
@mtusnio the branch seems to have some conflicts, which prevents the pull request from merging

**Comment by mtusnio** [comment]
Rebased it on top of 3.0-mikro-e, there was a merge conflict in the Readme.

**Review by nikhil-zinjurde-imgtec — APPROVED** [review]

**Pull request closed without merging**
