### PR TITLE
cpu/pic32/lib: add i2c driver

### PR DESCRIPTION
**Pull request by onkarkshirsagar**
Also add test-i2c application in platform/mikro-e/apps and fix CONTIKI_PLAT_DEFS in platform/mikro-e/Makefile.mikro-e

Signed-off-by: Onkar Kshirsagar onkarkshirsagar3@gamil.com

### CODE REVIEW

**Comment by nikhil-zinjurde-imgtec** [comment]
test with jenkins

**Comment by nikhil-zinjurde-imgtec** [comment]
build ci

**Comment by nikhil-zinjurde-imgtec** [comment]
build ci

**Comment by nikhil-zinjurde-imgtec** [comment]
test with jenkins

**Comment by nikhil-zinjurde-imgtec** [comment]
test with jenkins

**Comment by nikhil-zinjurde-imgtec** [comment]
test with jenkins

**Comment by abhijit-mahajani-imgtec** [comment]
New #15 has been opened for closing this one, as its outdated.

**Pull request closed without merging**
