### PR TITLE
I2C driver refactoring & NACK bit set

### PR DESCRIPTION
**Pull request by mtusnio**
Cleaned up function names to be more consistent (send_start & send_byte instead of send_start and byte_send, renamed burst_receive to just receive_bytes), added NACK to support all clicks.

### CODE REVIEW

**Comment by manohar-narkhede-imgtec** [comment]
Approved.

**Comment by manohar-narkhede-imgtec** [comment]
Please add API related changes for Proximity Click also.

**Comment by mtusnio** [comment]
Changed Proximity Click API calls.

**Comment by manohar-narkhede-imgtec** [comment]
Approved.

**Pull request merged**
